// <auto-generated />
using CoffeeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:Espresso.jpg",
                            IsTrendingProduct = false,
                            Name = "America",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:White_coffee_in_Vietnam.jpg",
                            IsTrendingProduct = false,
                            Name = "VietNam",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:Kafae_boran_Chiang_Mai.jpg",
                            IsTrendingProduct = false,
                            Name = "United Kingdom",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:Latte_macchiato_with_coffee_beans.jpg",
                            IsTrendingProduct = false,
                            Name = "India",
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:Mug_of_coffee_at_Black_Lion_High_Roding,_Essex,_England.jpg",
                            IsTrendingProduct = false,
                            Name = "Russia",
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "New product",
                            ImgUrl = "https://vi.wikipedia.org/wiki/T%E1%BA%ADp_tin:Latte.jpg",
                            IsTrendingProduct = false,
                            Name = "France",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("CoffeeShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("CoffeeShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("CoffeeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
